apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ojs-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:khalilahmad0334/OJS.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
